# Generated by Django 3.1.2 on 2020-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
