# Generated by Django 3.1.2 on 2020-10-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpl', '0004_auto_20201031_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_games',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gpl.lists'),
        ),
    ]
