# Generated by Django 3.1.2 on 2020-10-31 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='list_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_game', models.CharField(max_length=50)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.lists')),
            ],
        ),
    ]
