# Generated by Django 3.1.2 on 2020-10-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201031_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='list_owner',
            field=models.ForeignKey(default='6l0KFX7uojfZL8isN5XnB2H2aB53', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='API.users'),
            preserve_default=False,
        ),
    ]
