# Generated by Django 3.1.2 on 2020-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201031_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_games',
            name='background_image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_games',
            name='game_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
